version: 2.1
orbs:
  yarn: checkmoney/yarn@1.0.0
  docker: checkmoney/docker@1.1.0
  deploy: checkmoney/deploy@1.2.3
workflows:
  version: 2
  build:
    jobs:
      - yarn/local:
          name: eslint
          command: 'lint:code'
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - docker/build_push:
          org_name: 'igorkamyshev'
          image_name: 'pikcha'
          image_version: CIRCLE_TAG
          docker_username: DOCKER_USERNAME
          docker_password: DOCKER_PASSWORD
          filters:
            branches:
              only: master
            tags:
              only: /.*/
          requires:
            - eslint